CMakeLists.txt, Zufall.h, test/ZufallTest.cpp, test/catch.hpp, test/unit_tests.cpp, unit_tests.cpp
- added Catch header
- added first tests
- added folder for tests and moved the tests there
- fixed a typo in `Zufall` comments
- updated `CMakeList.txt`
- will close #55 and #51
- made with love.
=> Please merge Issue55 (add tests)

.gitignore, source/Leviathan/Configuration.cpp, source/Leviathan/Configuration.h, source/Leviathan/LeviathanDevice.cpp, source/Leviathan/LeviathanDevice.h, source/Leviathan/leviathan.h, test/ConfigurationTest.cpp, test/LeviathanDeviceTest.cpp, test/LoggerTest.cpp, test/Testhelper.cpp, test/Testhelper.h
- added new INI configuration reader to game engine
- added file writer to Testhelper
- will close #41
=> Add configuration to engine

CMakeLists.txt, source/new_game_code/main.cpp
- created new binary for new game code
- updated source file lists
We let the new game use leviathan Timers furthermore.
=> divide old and new game code

source/Leviathan/Configuration.cpp, source/Leviathan/Configuration.h, source/Leviathan/LeviathanDevice.h, source/Leviathan/Logger.cpp, source/Leviathan/Logger.h, source/Leviathan/TimeControl.cpp, source/Leviathan/TimeControl.h, source/Leviathan/Timer.h, test/ConfigurationTest.cpp, test/LoggerTest.cpp
=> Leviathan c++14

CMakeLists.txt, Changelog.md, source/Leviathan/Configuration.cpp, source/Leviathan/GameState.h, source/Leviathan/GameStateManager.cpp, source/Leviathan/GameStateManager.h, source/Leviathan/LeviathanDevice.cpp, source/Leviathan/LeviathanDevice.h, source/Leviathan/leviathan.h, source/new_game_code/GameStatePlay.cpp, source/new_game_code/GameStatePlay.h, source/new_game_code/main.cpp, test/GameStateManagerTest.cpp, test/GameStateTest.cpp, test/LeviathanDeviceTest.cpp
- Added game state interface
- Added game state manager
- Added a game loop to the engine
- Cleaned up
- All tested except the game loop
=> Add game states to engine

Changelog.md, source/Leviathan/Configuration.cpp, source/Leviathan/Configuration.h, source/Leviathan/GameState.h, source/Leviathan/GameStateManager.cpp, source/Leviathan/GameStateManager.h, source/Leviathan/LeviathanDevice.cpp, source/Leviathan/LeviathanDevice.h, source/Leviathan/Logger.cpp, source/Leviathan/Logger.h, source/Leviathan/MapWithDefault.h, source/Leviathan/TimeControl.cpp, source/Leviathan/TimeControl.h, source/Leviathan/Timer.cpp, source/Leviathan/Timer.h, source/new_game_code/GameStatePlay.cpp, source/new_game_code/GameStatePlay.h, test/ConfigurationTest.cpp, test/GameStateManagerTest.cpp, test/GameStateTest.cpp, test/LeviathanDeviceTest.cpp, test/LoggerTest.cpp, test/TimeControlTest.cpp, test/TimerTest.cpp, test/ZufallTest.cpp, test/helpers/Testhelper.cpp, test/helpers/Testhelper.h, test/helpers/TesthelperLeviathanDevice.h, test/unit_tests.cpp
- interchange Irrlicht types and containers with STL ones, and using their convenience methods
- remove Irrlicht inclusion wherever possible
- add Configuration tests for unknown keys
- add usage of nullptr instead of 0
- tidy up code
- will close #85
=> Decouple irrlicht

source/Leviathan/Mouse.cpp, source/Leviathan/Mouse.h, test/LeviathanDeviceTest.cpp, test/MouseTest.cpp
=> Add mouse wheel convenience methods

CMakeLists.txt, README.md, cmake/Modules/FindCatch.cmake, cmake/Modules/FindFakeIt.cmake, cmake/compilerFlags.cmake, source/Leviathan/CMakeLists.txt, source/chroniken_alt/CMakeLists.txt, source/new_game_code/CMakeLists.txt, test/CMakeLists.txt
... more like a LOT of CMake cleanup.
=> Folder cleanup

source/Leviathan/Configuration.cpp, source/Leviathan/Configuration.h, source/Leviathan/EventReceiver.cpp, source/Leviathan/EventReceiver.h, source/Leviathan/GameStateManager.cpp, source/Leviathan/GameStateManager.h, source/Leviathan/Keyboard.h, source/Leviathan/Mouse.h, source/Leviathan/TimeControl.cpp, source/Leviathan/TimeControl.h, source/Leviathan/Timer.h
=> Refactor explicitely default ctors and dtors

CMakeLists.txt, cmake/Modules/cotire.cmake, source/Leviathan/CMakeLists.txt, source/chroniken_alt/CMakeLists.txt, source/chroniken_alt/SaveGames.cpp, source/new_game_code/CMakeLists.txt, test/CMakeLists.txt
- added cotire, build process now signficantly faster than before
- fixed minor bug in old code
- will close #87
=> Add cotire to build chain

bootstrap_osx.sh, source/Leviathan/LeviathanDevice.cpp, source/Leviathan/LeviathanDevice.h, source/Leviathan/core/Configuration.cpp, source/Leviathan/core/Configuration.h, source/Leviathan/core/GameStateManager.cpp, source/new_game_code/GameStatePlay.h, source/new_game_code/GameStateShutdown.h, source/new_game_code/main.cpp, test/LeviathanDeviceTest.cpp, test/core/ConfigurationTest.cpp, test/helpers/TesthelperLeviathanDevice.cpp, test/helpers/TesthelperLeviathanDevice.h
This PR does
- init in ctor in LeviathanDevice and Configuration
- use reference for Logger instead of pointer
- update tests and mocks
- fix some codefactor offenses
=> Init in ctor only

source/Leviathan/LeviathanDevice.cpp, source/Leviathan/LeviathanDevice.h, source/Leviathan/core/GameStateManager.cpp, source/Leviathan/core/GameStateManager.h, source/Leviathan/core/Logger.cpp, source/Leviathan/core/Logger.h, source/new_game_code/main.cpp, test/LeviathanDeviceTest.cpp, test/core/GameStateManagerTest.cpp, test/core/LoggerTest.cpp, test/helpers/Testhelper.cpp, test/helpers/Testhelper.h
This PR will
- replace Leviathan exit code with proper log messages and exceptions
- handle error on graphic device creation
- add logging to GameStateManager
- log error cases and raise if unable to be handled
- clear text in Logger on write
Will close #109
=> Exception handling

CMakeLists.txt, game.log, source/Leviathan/CMakeLists.txt, source/Leviathan/LeviathanDevice.cpp, source/Leviathan/LeviathanDevice.h, source/Leviathan/core/GameStateManager.h, source/Leviathan/leviathan.h, source/Leviathan/video/Constants.h, source/Leviathan/video/MousePointerControl.cpp, source/Leviathan/video/MousePointerControl.h, source/new_game_code/CMakeLists.txt, source/new_game_code/GameStatePlay.cpp, test/CMakeLists.txt, test/LeviathanDeviceTest.cpp, test/core/ConfigurationTest.cpp, test/core/GameStateManagerTest.cpp, test/helpers/AttributesMock.hpp, test/helpers/CatchPatches.hpp, test/helpers/FakeitPatches.hpp, test/helpers/Testhelper.h, test/helpers/VideoDriverMock.hpp, test/input/ActionsTest.cpp, test/video/MousePointerControlTest.cpp
This PR will
- add mouse pointer control to the Leviathan Engine
- add draw routine surroundings to LeviathanDevice.run
- use the new features in the game
- add mocks and patches to the tests
- tidy up some comments
Will close #125
=> Add mouse pointer

.clang-format, README.md, source/Leviathan/CMakeLists.txt, source/Leviathan/LeviathanDevice.cpp, source/Leviathan/core/Configuration.cpp, source/Leviathan/core/Configuration.h, source/Leviathan/gui/Menu.cpp, source/Leviathan/gui/Menu.h, source/Leviathan/gui/MenuControl.cpp, source/Leviathan/gui/MenuControl.h, source/Leviathan/gui/types.h, source/Leviathan/input/Actions.cpp, source/Leviathan/input/Actions.h, source/Leviathan/input/EventReceiver.cpp, source/Leviathan/input/EventReceiver.h, source/Leviathan/video/types.h, source/new_game_code/CMakeLists.txt, source/new_game_code/GameStateMainMenu.cpp, test/core/ConfigurationTest.cpp, test/core/RandomizerTest.cpp, test/gui/MenuControlTest.cpp, test/helpers/IGUIImageMock.hpp, test/helpers/IImageMock.hpp
This PR will
- fix access violations in Actions and EventReceiver
- hide menu objects and some Irrlicht internals
- add buttons to menues
- enhance Game with menues and buttons
- update README
- some refactorings
Button eventing still missing!
Belongs to https://github.com/dixx/Die_Chroniken_eines_namenlosen_Spiels/issues/127
=> Enhance game menus

source/Leviathan/LeviathanDevice.h, source/Leviathan/core/GameStateManager.cpp, source/Leviathan/core/Logger.cpp, source/Leviathan/core/Logger.h, source/Leviathan/core/TimeControl.h, source/Leviathan/gui/types.h, source/Leviathan/input/Actions.cpp, source/Leviathan/input/Actions.h, source/Leviathan/input/EventToActionConverter.h, source/Leviathan/input/GUIEventActions.h, source/Leviathan/input/IActionConsumer.h, source/Leviathan/input/KeyboardEventActions.h, source/Leviathan/input/MouseEventActions.h
Will close https://github.com/dixx/Die_Chroniken_eines_namenlosen_Spiels/issues/135
=> Clean up includes

source/Leviathan/LeviathanDevice.cpp, source/Leviathan/LeviathanDevice.h
Closes https://github.com/dixx/Die_Chroniken_eines_namenlosen_Spiels/issues/120
It's still not optimal, but further refactoring lead to less readable and less performant code.
=> Refactor game loop

source/Leviathan/CMakeLists.txt, source/Leviathan/LeviathanDevice.cpp, source/Leviathan/LeviathanDevice.h, source/Leviathan/characters/Hero.cpp, source/Leviathan/leviathan.h, source/Leviathan/video/MeshHelper.cpp, source/Leviathan/video/MeshHelper.h, source/Leviathan/video/types.h, source/Leviathan/world/Ground.cpp, source/Leviathan/world/Ground.h, source/Leviathan/world/types.h, source/new_game_code/CMakeLists.txt, source/new_game_code/GameStateLoadGame.cpp, source/new_game_code/GameStateLoadGame.h, source/new_game_code/GameStateMainMenu.cpp, source/new_game_code/GameStatePlay.cpp, source/new_game_code/defines.h, source/new_game_code/main.cpp, test/CMakeLists.txt, test/LeviathanDeviceTest.cpp, test/world/GroundTest.cpp
=> Add world::Ground

data/action_mappings.yaml, src/Leviathan/input/Actions.cpp, src/Leviathan/input/Input.cpp, src/Leviathan/input/Input.h, src/Leviathan/input/KeyboardEventActions.cpp, src/Leviathan/input/KeyboardEventActions.h, src/Leviathan/input/MouseEventActions.cpp, src/Leviathan/input/MouseEventActions.h, tests/input/ActionsTest.cpp
...to make it more clear what to expect from these attributes.
=> Rename keyboard and mouse input `id` to `code`

include/Leviathan/core/IGameState.h, src/new_game_code/GameStateLoadGame.cpp, src/new_game_code/GameStateLoadGame.h, src/new_game_code/GameStateMainMenu.h, src/new_game_code/GameStatePlay.h, src/new_game_code/GameStateShutdown.cpp, src/new_game_code/GameStateShutdown.h
Will close https://github.com/dixx/Die_Chroniken_eines_namenlosen_Spiels/issues/140
=> Simplify IGameState

include/Leviathan/gui/IMousePointerControl.h, src/Leviathan/characters/Hero.cpp, src/Leviathan/core/Configuration.cpp, src/Leviathan/core/Configuration.h, src/Leviathan/gui/MousePointerControl.cpp, src/Leviathan/gui/MousePointerControl.h, src/Leviathan/world/NodeManager.cpp, src/Leviathan/world/NodeManager.h, src/new_game_code/GameStateMainMenu.cpp, src/new_game_code/GameStatePlay.cpp, tests/core/ConfigurationTest.cpp, tests/gui/MousePointerControlTest.cpp, tests/world/NodeManagerTest.cpp
Belongs to https://github.com/dixx/Die_Chroniken_eines_namenlosen_Spiels/issues/149
=> Rename add and create methods consistently

src/Leviathan/characters/Hero.h, src/Leviathan/characters/Heroes.h, src/Leviathan/core/Configuration.h, src/Leviathan/core/GameStateManager.h, src/Leviathan/core/Logger.h, src/Leviathan/core/Randomizer.h, src/Leviathan/core/TimeControl.h, src/Leviathan/core/Timer.h, src/Leviathan/gui/Menu.h, src/Leviathan/gui/MenuControl.h, src/Leviathan/gui/MousePointerControl.h, src/Leviathan/input/Actions.h, src/Leviathan/input/EventReceiver.h, src/Leviathan/input/GUIEventActions.h, src/Leviathan/input/KeyboardEventActions.h, src/Leviathan/input/MouseEventActions.h, src/Leviathan/video/GraphicEngine.h, src/Leviathan/video/Textures.h, src/new_game_code/GameStateLoadGame.h, src/new_game_code/GameStateMainMenu.h, src/new_game_code/GameStatePlay.h, src/new_game_code/GameStateShutdown.h
Closes https://github.com/dixx/Die_Chroniken_eines_namenlosen_Spiels/issues/178
=> Clean up boiler plate

src/Leviathan/LeviathanDevice.cpp, src/Leviathan/gui/MenuControl.cpp, src/Leviathan/gui/MenuControl.h, src/Leviathan/gui/MousePointerControl.cpp, src/Leviathan/gui/MousePointerControl.h, src/Leviathan/input/EventReceiver.cpp, src/Leviathan/input/EventReceiver.h, src/Leviathan/video/Camera.cpp, src/Leviathan/video/Camera.h, src/Leviathan/video/Textures.cpp, src/Leviathan/video/Textures.h, src/Leviathan/world/Character.cpp, src/Leviathan/world/Character.h, src/Leviathan/world/GroundTile.cpp, src/Leviathan/world/GroundTile.h, src/Leviathan/world/NodeManager.cpp, src/Leviathan/world/NodeManager.h, tests/characters/HeroTest.cpp, tests/characters/HeroesTest.cpp, tests/world/GroundTest.cpp, tests/world/NodeManagerTest.cpp
Fixes https://github.com/dixx/Die_Chroniken_eines_namenlosen_Spiels/issues/173
=> Refactor textures usage

src/new_game_code/HeroMover.cpp, src/new_game_code/HeroMover.h
Belongs to https://github.com/dixx/Die_Chroniken_eines_namenlosen_Spiels/issues/30
=> Hero updates target as long as action is ongoing
